### ISSUE TITLE
It seems to be the elif statement

### ISSUE THREAD

**Issue by shumoLR** [edenartlab/eden_comfy_pipelines#19]
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.3\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI-aki-v1.3\custom_nodes\eden_comfy_pipelines\__init__.py", line 11, in <module>
    from img_utils.animation import Animation_RGB_Mask
  File "F:\ComfyUI-aki-v1.3\custom_nodes\eden_comfy_pipelines\img_utils\animation.py", line 20
    elif self.mode == "concentric_circles":
    ^^^^
SyntaxError: invalid syntax

Cannot import F:\ComfyUI-aki-v1.3\custom_nodes\eden_comfy_pipelines module for custom nodes: invalid syntax (animation.py, line 20)

**Comment by aiXander** [comment]
This should be fixed now!
