### ISSUE TITLE
problem with model downloads

### ISSUE THREAD

**Issue by coronald-cloud** [edenartlab/eden_comfy_pipelines#6]
Whenever I attempt to use this node I get the following error:

Interrogating image with mode fast, keep_model_alive=True
Loading caption model blip-large...
Cache_dir: C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\models\blip
model.safetensors:  22%|█████████████████████▍                                                                             | 408M/1.88G [00:35<02:08, 11.5MB/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\custom_nodes\eden_comfy_pipelines\clip_utils\clip_tools.py", line 69, in interrogate
    ci = self.load_ci(clip_model_path=clip_model_dir)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\custom_nodes\eden_comfy_pipelines\clip_utils\clip_tools.py", line 109, in load_ci
    self.ci = Interrogator(Config(clip_model_path=clip_model_path, clip_model_name="ViT-L-14/openai", cache_dir=BLIP_MODEL_DIR))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\custom_nodes\eden_comfy_pipelines\clip_utils\clip_interrogator.py", line 70, in __init__
    self.load_caption_model()
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\custom_nodes\eden_comfy_pipelines\clip_utils\clip_interrogator.py", line 86, in load_caption_model
    caption_model = BlipForConditionalGeneration.from_pretrained(model_path, torch_dtype=self.dtype, cache_dir=self.config.cache_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3190, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1492, in hf_hub_download
    http_get(
  File "C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 566, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 1879014680 but has size 407906605 (model.safetensors).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
------------------------------------------------------------------------------------------------------------------------------------

I am fairly certain its because I have bad internet, I have tried multiple times. would there be a way for me to MANUALLY install all the model files I would need to make this node work? and if so where would I put them?

**Comment by genekogan** [comment]
this is probably due to huggingface's outage. i would clear your hf cache and try again. otherwise, yeah you'd have to just download these manually.

**Comment by coronald-cloud** [comment]
what files from hugging face would I need? and what directory do they go in?

**Comment by coronald-cloud** [comment]
Hey all it is my internet, my isp is terrible. 

if anyone can help me out I'd love to use this node.
![image](https://github.com/edenartlab/eden_comfy_pipelines/assets/124480780/321a5d22-3f1e-4849-9696-e33778bad128)
I downloaded everything from this repo
when I put the model.safetensors file in the models/blip folder it never sees it and tries to download it

if someone can tell me where I need to put things manually I would be super grateful. like so

**"donwload this file, rename it to this, and put it in this directory"**
please include what the file path would be I don't know where things are. don't just say "in the directory" say
C:\Users\connr\Documents\comfy ui\ComfyUI_windows_portable\ComfyUI\models or something similar

I would really appreciate it, and I am trying to upgrade my internet but for now I have to manually downloads models.

**Comment by stanleyftf1005** [comment]
> this is probably due to huggingface's outage. i would clear your hf cache and try again. otherwise, yeah you'd have to just download these manually.



> this is probably due to huggingface's outage. i would clear your hf cache and try again. otherwise, yeah you'd have to just download these manually.

where do you place the model if download manually

**Comment by aiXander** [comment]
Added download instructions for this into the readme!
